// This file is generated by scripts/generate-event-data.cjs
// @generated
// Do not edit this file directly. Run 'node scripts/generate-event-data.cjs' to regenerate.

import type { EventData } from './eventData';
import { COLOR_SCALES } from '../../../../../styles/color-chart';

const retailColor = COLOR_SCALES.teal.colors[4];
const ecColor = COLOR_SCALES.indigo.colors[5];

// Retail Events
export const retailEvents: EventData[] = [
  { name: 'FY22 SMD', interval: [new Date(2022, 5, 2), new Date(2022, 5, 13)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy22-smd' },
  { name: 'FY22 WMD', interval: [new Date(2022, 11, 8), new Date(2022, 11, 19)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy22-wmd' },
  { name: 'FY23 SMD', interval: [new Date(2023, 5, 15), new Date(2023, 5, 26)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy23-smd' },
  { name: 'FY23 WMD', interval: [new Date(2023, 11, 7), new Date(2023, 11, 18)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy23-wmd' },
  { name: 'FY24 SMD', interval: [new Date(2024, 5, 3), new Date(2024, 5, 11)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy24-smd' },
  { name: 'FY24 D11', interval: [new Date(2024, 10, 1), new Date(2024, 10, 11)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy24-d11' },
  { name: 'FY24 WMD', interval: [new Date(2024, 11, 5), new Date(2024, 11, 16)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy24-wmd' },
  { name: 'FY24 FF', interval: [new Date(2025, 0, 5), new Date(2025, 0, 8)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy24-ff' },
  { name: 'FY24 CNY', interval: [new Date(2025, 0, 20), new Date(2025, 1, 9)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy24-cny' },
  { name: 'FY25 SMD', interval: [new Date(2025, 4, 27), new Date(2025, 5, 9)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy25-smd' },
  { name: 'FY25 618', interval: [new Date(2025, 5, 15), new Date(2025, 5, 20)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy25-618' },
  { name: 'FY25 D11', interval: [new Date(2025, 9, 20), new Date(2025, 10, 11)], backgroundColor: retailColor, backgroundOpacity: 0.32, channel: 'Retail', link: 'https://example.com/events/fy25-d11' },
];

// EC Events
export const ecEvents: EventData[] = [
  { name: 'FY23 IWD', interval: [new Date(2023, 2, 4), new Date(2023, 2, 8)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-iwd' },
  { name: 'FY23 SBD', interval: [new Date(2023, 3, 10), new Date(2023, 3, 11)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-sbd' },
  { name: 'FY23 618', interval: [new Date(2023, 4, 31), new Date(2023, 5, 20)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-618' },
  { name: 'FY23 SMD', interval: [new Date(2023, 5, 15), new Date(2023, 5, 26)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-smd' },
  { name: 'FY23 周年庆', interval: [new Date(2023, 6, 25), new Date(2023, 6, 28)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-周年庆' },
  { name: 'FY23 99', interval: [new Date(2023, 8, 6), new Date(2023, 8, 9)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-99' },
  { name: 'FY23 D11', interval: [new Date(2023, 9, 31), new Date(2023, 10, 11)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-d11' },
  { name: 'FY23 WMD', interval: [new Date(2023, 11, 7), new Date(2023, 11, 18)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-wmd' },
  { name: 'FY23 D12', interval: [new Date(2023, 11, 9), new Date(2023, 11, 12)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy23-d12' },
  { name: 'FY24 IWD', interval: [new Date(2024, 1, 28), new Date(2024, 2, 8)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-iwd' },
  { name: 'FY24 618', interval: [new Date(2024, 4, 20), new Date(2024, 5, 20)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-618' },
  { name: 'FY24 SMD', interval: [new Date(2024, 5, 3), new Date(2024, 5, 11)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-smd' },
  { name: 'FY24 周年庆', interval: [new Date(2024, 6, 15), new Date(2024, 6, 19)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-周年庆' },
  { name: 'FY24 狂暑季', interval: [new Date(2024, 6, 15), new Date(2024, 6, 19)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-狂暑季' },
  { name: 'FY24 SBD', interval: [new Date(2024, 8, 16), new Date(2024, 8, 22)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-sbd' },
  { name: 'FY24 D11', interval: [new Date(2024, 9, 21), new Date(2024, 10, 11)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-d11' },
  { name: 'FY24 WMD', interval: [new Date(2024, 11, 5), new Date(2024, 11, 16)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-wmd' },
  { name: 'FY24 D12', interval: [new Date(2024, 11, 9), new Date(2024, 11, 12)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-d12' },
  { name: 'FY24 FF', interval: [new Date(2025, 0, 5), new Date(2025, 0, 8)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-ff' },
  { name: 'FY24 CNY', interval: [new Date(2025, 0, 20), new Date(2025, 1, 9)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy24-cny' },
  { name: 'FY25 IWD', interval: [new Date(2025, 1, 26), new Date(2025, 2, 8)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy25-iwd' },
  { name: 'FY25 618', interval: [new Date(2025, 4, 16), new Date(2025, 5, 20)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy25-618' },
  { name: 'FY25 SMD', interval: [new Date(2025, 4, 27), new Date(2025, 5, 9)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy25-smd' },
  { name: 'FY25 SBD', interval: [new Date(2025, 8, 12), new Date(2025, 8, 18)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy25-sbd' },
  { name: 'FY25 D11', interval: [new Date(2025, 9, 20), new Date(2025, 10, 11)], backgroundColor: ecColor, backgroundOpacity: 0.32, channel: 'EC', link: 'https://example.com/events/fy25-d11' },
];

// All Events (Retail + EC)
export const generatedEvents: EventData[] = [...retailEvents, ...ecEvents];
